version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinemadmin
      MYSQL_PASSWORD: pass4cinemadmin