spring:
  data:
    jdbc:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/cinema?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: cinemadmin
    password: pass4cinemadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-stacktrace: never
  port: 8080